### ISSUE TITLE
OOM Crash

### ISSUE THREAD

**Issue by robohorse** [team-supercharge/ShimmerLayout#40]
Hi, here is some problems:

```java
Android: 4.1.2
Manufacturer: samsung
Model: GT-S7390
Thread: main-1

java.lang.OutOfMemoryError
	at android.graphics.Bitmap.nativeCreate(Bitmap.java)
	at android.graphics.Bitmap.createBitmap(Bitmap.java:669)
	at android.graphics.Bitmap.createBitmap(Bitmap.java:649)
	at io.supercharge.shimmerlayout.ShimmerLayout.createBitmap(ShimmerLayout.java:320)
	at io.supercharge.shimmerlayout.ShimmerLayout.getDestinationBitmap(ShimmerLayout.java:249)
	at io.supercharge.shimmerlayout.ShimmerLayout.dispatchDrawUsingBitmap(ShimmerLayout.java:184)
	at io.supercharge.shimmerlayout.ShimmerLayout.dispatchDraw(ShimmerLayout.java:100)
	at android.view.View.draw(View.java:13825)
	at android.widget.FrameLayout.draw(FrameLayout.java:467)
	at android.view.View.getDisplayList(View.java:12773)
	at android.view.View.getDisplayList(View.java:12817)
	at android.view.View.draw(View.java:13546)
	at android.view.ViewGroup.drawChild(ViewGroup.java:3226)
	at android.support.v7.widget.RecyclerView.drawChild(RecyclerView.java:4581)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3091)
	at android.view.View.draw(View.java:13825)
	at android.support.v7.widget.RecyclerView.draw(RecyclerView.java:3987)
	at android.view.View.getDisplayList(View.java:12773)
	at android.view.View.getDisplayList(View.java:12817)
	at android.view.View.draw(View.java:13546)
	at android.view.ViewGroup.drawChild(ViewGroup.java:3226)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3091)
	at android.view.View.getDisplayList(View.java:12771)
	at android.view.View.getDisplayList(View.java:12817)
	at android.view.View.draw(View.java:13546)
	at android.view.ViewGroup.drawChild(ViewGroup.java:3226)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3091)
	at android.view.View.getDisplayList(View.java:12771)
	at android.view.View.getDisplayList(View.java:12817)
	at android.view.View.draw(View.java:13546)
	at android.view.ViewGroup.drawChild(ViewGroup.java:3226)
	at android.support.design.widget.CoordinatorLayout.drawChild(CoordinatorLayout.java:1229)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3091)
	at android.view.View.getDisplayList(View.java:12771)
	at android.view.View.getDisplayList(View.java:12817)
	at android.view.View.draw(View.java:13546)
	at android.view.ViewGroup.drawChild(ViewGroup.java:3226)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3091)
	at android.view.View.draw(View.java:13825)
	at android.widget.FrameLayout.draw(FrameLayout.java:467)
	at android.view.View.getDisplayList(View.java:12773)
	at android.view.View.getDisplayList(View.java:12817)
	at android.view.View.draw(View.java:13546)
	at android.view.ViewGroup.drawChild(ViewGroup.java:3226)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3091)
	at android.view.View.getDisplayList(View.java:12771)
	at android.view.View.getDisplayList(View.java:12817)
	at android.view.View.draw(View.java:13546)
	at android.view.ViewGroup.drawChild(ViewGroup.java:3226)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3091)
	at android.view.View.getDisplayList(View.java:12771)
	at android.view.View.getDisplayList(View.java:12817)
	at android.view.View.draw(View.java:13546)
	at android.view.ViewGroup.drawChild(ViewGroup.java:3226)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3091)
	at android.view.View.getDisplayList(View.java:12771)
	at android.view.View.getDisplayList(View.java:12817)
	at android.view.View.draw(View.java:13546)
	at android.view.ViewGroup.drawChild(ViewGroup.java:3226)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3091)
	at android.view.View.draw(View.java:13825)
	at android.widget.FrameLayout.draw(FrameLayout.java:467)
	at com.android.internal.policy.impl.PhoneWindow$DecorView.draw(PhoneWindow.java:2458)
	at android.view.View.getDisplayList(View.java:12773)
	at android.view.View.getDisplayList(View.java:12817)
	at android.view.HardwareRenderer$GlRenderer.draw(HardwareRenderer.java:1144)
	at android.view.ViewRootImpl.draw(ViewRootImpl.java:2313)
	at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2185)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1993)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1143)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:4684)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:725)
	at android.view.Choreographer.doCallbacks(Choreographer.java:555)
	at android.view.Choreographer.doFrame(Choreographer.java:525)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:711)
	at android.os.Handler.handleCallback(Handler.java:615)
	at android.os.Handler.dispatchMessage(Handler.java:92)
	at android.os.Looper.loop(Looper.java:177)
	at android.app.ActivityThread.main(ActivityThread.java:4947)
	at java.lang.reflect.Method.invokeNative(Method.java)
	at java.lang.reflect.Method.invoke(Method.java:511)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1038)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:805)
	at dalvik.system.NativeStart.main(NativeStart.java)
```

**Comment by robohorse** [comment]
https://github.com/team-supercharge/ShimmerLayout/blob/a05ee98f0fb843847902ff2a79282eabacabf3aa/shimmerlayout/src/main/java/io/supercharge/shimmerlayout/ShimmerLayout.java#L375

System.gc() sends a request to the GC to perform a collection cycle. This request may be served or it may be ignored, therefore neither result should be relied on.


Previous stacktrace is from version 1.0.2. I updated my dependency to the current version and found the crash on that lines.

**Comment by veghtomi** [comment]
@robohorse thanks for reporting the issue. I see that you used it in a RecyclerView. Unfortunately, that usage still consumes a lot of memory especially on phones with high-resolution screens, but I am working on the solution.

**Comment by robohorse** [comment]
del

**Comment by veghtomi** [comment]
@robohorse I created the solution for this, waiting to be reviewed. Until then, you can test it!

**Comment by veghtomi** [comment]
@robohorse the new 1.2.0 version solves your issue

**Comment by veghtomi** [comment]
@robohorse Check out the new 2.0.0 version where memory usage decreased dramatically.
