### ISSUE TITLE
IllegalArgumentException: width and height must be > 0

### ISSUE THREAD

**Issue by kavitamp** [team-supercharge/ShimmerLayout#53]
I am getting this error in ShimmerLayout class. What could be the issue?

Fatal Exception: java.lang.IllegalArgumentException: width and height must be > 0
       at android.graphics.Bitmap.createBitmap(Bitmap.java:969)
       at android.graphics.Bitmap.createBitmap(Bitmap.java:948)
       at android.graphics.Bitmap.createBitmap(Bitmap.java:915)
       at io.supercharge.shimmerlayout.ShimmerLayout.createBitmap(ShimmerLayout.java:317)
       at io.supercharge.shimmerlayout.ShimmerLayout.getSourceMaskBitmap(ShimmerLayout.java:273)
       at io.supercharge.shimmerlayout.ShimmerLayout.drawMask(ShimmerLayout.java:203)
       at io.supercharge.shimmerlayout.ShimmerLayout.dispatchDrawUsingBitmap(ShimmerLayout.java:193)
       at io.supercharge.shimmerlayout.ShimmerLayout.dispatchDraw(ShimmerLayout.java:100)

**Comment by veghtomi** [comment]
@kavitamp try the newest version of the library (2.1.0)

**Comment by veghtomi** [comment]
@kavitamp is it working now as expected?

**Comment by kavitamp** [comment]
@veghtomi This error is not coming frequently. I have not tries it yet. Will let you know once it will get tested.

**Comment by veghtomi** [comment]
@kavitamp ok, in the meantime I close this issue since with the new version it cannot happen. If it happens, just open the issue again.

**Comment by kavitamp** [comment]
Sure. Thank you
