### ISSUE TITLE
ColorSoftDarkModeManager.java line 645 com.color.darkmode.ColorSoftDarkModeManager.handleShader

### ISSUE THREAD

**Issue by rezastallone** [team-supercharge/ShimmerLayout#91]
I get the following error on my Crashlytic dashboard.

I am not sure how to reproduce. Can you guys help me out ? Thanks

Fatal Exception: java.lang.IllegalArgumentException: Shader parameters must not be null
       at android.graphics.ComposeShader.<init>(ComposeShader.java:79)
       at android.graphics.ComposeShader.getDarkModeShader(ComposeShader.java:111)
       at com.color.darkmode.ColorSoftDarkModeManager.handleShader(ColorSoftDarkModeManager.java:645)
       at com.color.darkmode.ColorSoftDarkModeManager.changePaintWhenDrawArea(ColorSoftDarkModeManager.java:450)
       at com.color.darkmode.ColorSoftDarkModeManager.changePaintWhenDrawArea(ColorSoftDarkModeManager.java:472)
       at com.color.darkmode.ColorDarkModeManager.changePaintWhenDrawArea(ColorDarkModeManager.java:905)
       at android.graphics.OppoBaseBaseCanvas.changeArea(OppoBaseBaseCanvas.java:117)
       at android.graphics.BaseRecordingCanvas.drawRect(BaseRecordingCanvas.java:557)
       at io.supercharge.shimmerlayout.ShimmerLayout.ɩ(:261)
       at io.supercharge.shimmerlayout.ShimmerLayout.ι(:250)
       at io.supercharge.shimmerlayout.ShimmerLayout.dispatchDraw(:106)
       at android.view.View.draw(View.java:21820)
       at android.view.View.updateDisplayListIfDirty(View.java:20642)
       at android.view.View.draw(View.java:21525)
       at android.view.ViewGroup.drawChild(ViewGroup.java:4542)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4279)
       at androidx.constraintlayout.widget.ConstraintLayout.dispatchDraw(:2023)
       at android.view.View.updateDisplayListIfDirty(View.java:20633)
       at android.view.View.draw(View.java:21525)
       at android.view.ViewGroup.drawChild(ViewGroup.java:4542)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4279)
       at android.view.View.updateDisplayListIfDirty(View.java:20633)
       at android.view.View.draw(View.java:21525)
       at android.view.ViewGroup.drawChild(ViewGroup.java:4542)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4279)
       at androidx.constraintlayout.widget.ConstraintLayout.dispatchDraw(:2023)
       at android.view.View.updateDisplayListIfDirty(View.java:20633)
       at android.view.View.draw(View.java:21525)
       at android.view.ViewGroup.drawChild(ViewGroup.java:4542)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4279)
       at androidx.constraintlayout.widget.ConstraintLayout.dispatchDraw(:2023)
       at android.view.View.updateDisplayListIfDirty(View.java:20633)
       at android.view.View.draw(View.java:21525)
       at android.view.ViewGroup.drawChild(ViewGroup.java:4542)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4279)
       at android.view.View.draw(View.java:21820)
       at androidx.core.widget.NestedScrollView.draw(:1998)
       at android.view.View.updateDisplayListIfDirty(View.java:20642)
       at android.view.View.draw(View.java:21525)
       at android.view.ViewGroup.drawChild(ViewGroup.java:4542)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4279)
       at android.view.View.draw(View.java:21820)
       at android.view.View.updateDisplayListIfDirty(View.java:20642)
       at android.view.View.draw(View.java:21525)
       at android.view.ViewGroup.drawChild(ViewGroup.java:4542)
       at androidx.coordinatorlayout.widget.CoordinatorLayout.drawChild(:1277)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4279)
       at android.view.View.updateDisplayListIfDirty(View.java:20633)
       at android.view.View.draw(View.java:21525)
       at android.view.ViewGroup.drawChild(ViewGroup.java:4542)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4279)
       at android.view.View.draw(View.java:21820)
       at androidx.viewpager.widget.ViewPager.draw(:2426)
       at android.view.View.updateDisplayListIfDirty(View.java:20642)
       at android.view.View.draw(View.java:21525)
       at android.view.ViewGroup.drawChild(ViewGroup.java:4542)
       at androidx.coordinatorlayout.widget.CoordinatorLayout.drawChild(:1277)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4279)
       at android.view.View.updateDisplayListIfDirty(View.java:20633)
       at android.view.View.draw(View.java:21525)
       at android.view.ViewGroup.drawChild(ViewGroup.java:4542)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4279)
       at android.view.View.draw(View.java:21820)
       at androidx.viewpager.widget.ViewPager.draw(:2426)
       at android.view.View.updateDisplayListIfDirty(View.java:20642)
       at android.view.View.draw(View.java:21525)
       at android.view.ViewGroup.drawChild(ViewGroup.java:4542)
       at androidx.coordinatorlayout.widget.CoordinatorLayout.drawChild(:1277)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4279)
       at android.view.View.draw(View.java:21820)
       at android.view.View.updateDisplayListIfDirty(View.java:20642)
       at android.view.View.draw(View.java:21525)
       at android.view.ViewGroup.drawChild(ViewGroup.java:4542)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4279)
       at android.view.View.updateDisplayListIfDirty(View.java:20633)
       at android.view.View.draw(View.java:21525)
       at android.view.ViewGroup.drawChild(ViewGroup.java:4542)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4279)
       at android.view.View.updateDisplayListIfDirty(View.java:20633)
       at android.view.View.draw(View.java:21525)
       at android.view.ViewGroup.drawChild(ViewGroup.java:4542)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4279)
       at android.view.View.updateDisplayListIfDirty(View.java:20633)
       at android.view.View.draw(View.java:21525)
       at android.view.ViewGroup.drawChild(ViewGroup.java:4542)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4279)
       at android.view.View.updateDisplayListIfDirty(View.java:20633)
       at android.view.View.draw(View.java:21525)
       at android.view.ViewGroup.drawChild(ViewGroup.java:4542)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4279)
       at android.view.View.draw(View.java:21820)
       at com.android.internal.policy.DecorView.draw(DecorView.java:869)
       at android.view.View.updateDisplayListIfDirty(View.java:20642)
       at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:575)
       at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:581)
       at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:654)
       at android.view.ViewRootImpl.draw(ViewRootImpl.java:4125)
       at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:3913)
       at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3219)
       at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2050)
       at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:8455)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1057)
       at android.view.Choreographer.doCallbacks(Choreographer.java:881)
       at android.view.Choreographer.doFrame(Choreographer.java:808)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1042)
       at android.os.Handler.handleCallback(Handler.java:883)
       at android.os.Handler.dispatchMessage(Handler.java:100)
       at android.os.Looper.loop(Looper.java:237)
       at android.app.ActivityThread.main(ActivityThread.java:7830)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1040)

**Comment by Tukesboy** [comment]
Have you solved your problem?

**Comment by rezastallone** [comment]
> Have you solved your problem?

I honestly forgot about it, I think i solved it by updating the library
