### ISSUE TITLE
Attempt to invoke interface method 'long[] android.graphics.IShaderExt.getColorLongs()'

### ISSUE THREAD

**Issue by Tukesboy** [team-supercharge/ShimmerLayout#93]
java.lang.NullPointerException: Attempt to invoke interface method 'long[] android.graphics.IShaderExt.getColorLongs()' on a null object reference

	at android.graphics.ShaderExtImpl.getComposeShaderColor(ShaderExtImpl.java:76)

	at android.graphics.ShaderExtImpl.getComposeShaderColor(ShaderExtImpl.java:65)

	at com.oplus.darkmode.OplusDarkModeThirdInvertManager.getRealPaintState(OplusDarkModeThirdInvertManager.java:629)

	at com.oplus.darkmode.OplusDarkModeManager.getRealPaintState(OplusDarkModeManager.java:501)

	at android.graphics.BaseCanvasExtImpl.changeArea(BaseCanvasExtImpl.java:148)

	at android.graphics.BaseRecordingCanvas.drawRect(BaseRecordingCanvas.java:563)

	at io.supercharge.shimmerlayout.ShimmerLayout.b(ShimmerLayout.java:261)

	at io.supercharge.shimmerlayout.ShimmerLayout.a(ShimmerLayout.java:250)

	at io.supercharge.shimmerlayout.ShimmerLayout.dispatchDraw(ShimmerLayout.java:106)

	at android.view.View.draw(View.java:22938)

	at android.view.View.updateDisplayListIfDirty(View.java:21751)

	at android.view.View.draw(View.java:22637)

	at android.view.ViewGroup.drawChild(ViewGroup.java:4652)

	at androidx.recyclerview.widget.RecyclerView.drawChild(RecyclerView.java:5030)

**Comment by abhishekint16** [comment]
Hey, @Tukesboy could you fix this?
